version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/data:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_microservice_db

  user-common:
    build:
      context: .
      dockerfile: ./apps/user-common-microservice/Dockerfile
      args:
        - APP_ENV
    command: npm run start:dev user-common-microservice
    ports:
      - 3013:3000
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules/
    environment:
      DB_HOST: mysqldb
    env_file:
      - ./apps/user-common-microservice/.env
    depends_on:
      - mysqldb

volumes:
  node_modules:
  mysqldata:
